'use client';

import { Navigation } from '@components/Navigation';
import './globals.css';
import type { Metadata } from 'next';
import { Poppins, Outfit } from 'next/font/google';
import StyledComponentsRegistry from '@lib/registry';

const outfit = Outfit({ subsets: ['latin'], variable: '--outfit' });
const poppins = Poppins({ weight: ['400', '500'], subsets: ['latin'], variable: '--poppins' });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='fr'>
            <body className={`${poppins.className} ${poppins.variable} ${outfit.variable}`}>
                <StyledComponentsRegistry>
                    <Navigation />
                    {children}
                </StyledComponentsRegistry>
            </body>
        </html>
    );
}
